### ISSUE TITLE
optimize list needs to be rearranged

### ISSUE THREAD

**Issue by etri-edgeai** [etri-edgeai/nn-comp-evf#5]
![image](https://github.com/user-attachments/assets/6c5fa3cd-0930-4132-87d7-a43c2b986171)
this list needs to be rearrange, it is bugged

**Comment by junyong300** [comment]
fyi this is models we need to add three lines
![image](https://github.com/user-attachments/assets/c7d3376b-ddf2-444f-8e92-a3bb071e93e6)

**Comment by junyong300** [comment]
1. Update optimize.html

Add a second modal for editing. For example, beneath your “Create Optimization Modal,” add:


<div class="modal modal-blur fade" id="id_modal_edit_optimization" tabindex="-1">
  <div class="modal-dialog modal-xl modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Edit Optimization</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        
        <div class="row mb-3">
          <div class="col-md-6">
            <label class="form-label">Optimize Method Name</label>
            
            <input id="id_edit_optimize_method_name" type="text" class="form-control" readonly>
          </div>
          <div class="col-md-6">
            <label class="form-label">Original Model Name</label>
            <input id="id_edit_original_model_name" type="text" class="form-control" readonly>
          </div>
        </div>
        
        <div class="mt-3">
          <label class="form-label">optimize.py</label>
          <div id="editor_optimize_py_edit" class="editor"></div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-link link-secondary" data-bs-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-primary" id="id_edit_optimization_ok">Save Changes</button>
      </div>
    </div>
  </div>
</div>

Adjust styling/classes to match your own layout.
2. Update optimize.js (Frontend Logic)
2.1 Initialize the “Edit” Ace Editor

Somewhere near the top (or inside a suitable .on('shown.bs.modal', ...)) for your edit modal:

let editorOptimizePyEdit = null;

$('#id_modal_edit_optimization').on('shown.bs.modal', function () {
  if (!editorOptimizePyEdit) {
    editorOptimizePyEdit = ace.edit("editor_optimize_py_edit");
    editorOptimizePyEdit.setTheme("ace/theme/monokai");
    editorOptimizePyEdit.session.setMode("ace/mode/python");
    editorOptimizePyEdit.setOptions({
      maxLines: Infinity,
      minLines: 30
    });
  }
  editorOptimizePyEdit.resize(); 
});

And reset when hidden:

$('#id_modal_edit_optimization').on('hidden.bs.modal', function () {
  if (editorOptimizePyEdit) {
    editorOptimizePyEdit.setValue('', -1);
  }
  $('#id_edit_optimize_method_name').val('');
  $('#id_edit_original_model_name').val('');
});
